trainer:
  max_epochs: 50
  accelerator: auto
  strategy: auto
  devices: auto
  deterministic: false
  benchmark: true
  sync_batchnorm: true
  log_every_n_steps: 1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  num_sanity_val_steps: 1
  enable_model_summary: true
  reload_dataloaders_every_n_epochs: 0
  gradient_clip_val: 2.0
  gradient_clip_algorithm: norm
logger:
  save_dir: ./
  name: lightning_logs
progress_bar_callback:
  refresh_rate: 1
ckpt_callback:
  filename: '{epoch:02d}, {loss_epoch:.3f}'
  monitor: valid/loss_epoch
  save_top_k: 10
  mode: min
  save_last: True
  verbose: false
  save_weights_only: false
early_stop_callback:
  monitor: valid/loss_epoch
  min_delta: 0.01
  patience: 200
  mode: min
swa_callback:
  swa_lrs: 2e-4
  swa_epoch_start: 0.8
  annealing_epochs: 10
  annealing_strategy: cos
